// client/src/components/Wizard/Wizard.tsx
import * as React from 'react';
import {Link} from 'react-router-dom';
import SpellListRow from "./SpellListRow";

class Wizard extends React.Component<any, any> {
  public state = {
    spells: [
      {
        'name': "blast",
        'description': "Damages one enemy. Can also be used to break open some doors and chests.",
        'price': 1000,
      },
      {
        'name': "heal",
        'description': "Heals you or a friend.",
        'price': 500
      },
      {
        'name': "power",
        'description': "Has an unpredictable effect which is different in every adventure. Common effects include teleportation, healing, causing earthquakes, or even resurrecting monsters.",
        'price': 100
      },
      {
        'name': "speed",
        'description': "Doubles your agility for a time, making you a better fighter.",
        'price': 4000
      },
    ],
  };

  public render() {

    if (!this.props.player) {
      return <p>Loading...</p>
    }

    return (
      <div className="wizard-shop">
        <h2><img src="/static/images/ravenmore/128/tome.png" />Hokas Tokas' School of Magick</h2>
        <p>After a few minutes of diligent searching, you find Hokas Tokas, the old Mage. He looks at you and says, &quot;So you want old Hokey to teach you some magic, eh? Well, it'll cost you. Here are the spells I teach. Which will it be?&quot;</p>
        <table className="table spells-list">
          <tr className="d-flex">
            <th className="col-sm-4 col-md-6">Spell</th>
            <th className="col-sm-3 col-md-2 text-center">Current Ability<br />
              <span className="small">Odds to cast successfully</span>
            </th>
            <th className="col-sm-3 col-md-2 text-center">Price</th>
            <th className="col-sm-2 col-md-2" />
          </tr>
          {this.state.spells.map(spell =>
            <SpellListRow key={spell.name} {...this.props} spell={spell} />
          )}
        </table>
        <p>You have {this.props.player.gold} gold pieces.</p>

        <Link to="/main-hall/hall" className="btn btn-primary">Done</Link>
      </div>
    );

  }

}

export default Wizard;

// static/main-hall/components/wizard.component.ts
import {Component,  OnInit}  from '@angular/core';
import {Router} from '@angular/router';

import {PlayerService} from '../services/player.service';
import {Game} from "../../core/models/game";

@Component({
  templateUrl: "/static/main-hall/templates/wizard.html",
})
export class WizardComponent implements OnInit  {
  public message: string;
  public error: string;

  public spells: any[] = [
    {
      'name': "blast",
      'description': "Damages one enemy. Can also be used to break open some doors and chests.",
      'price': 1000
    },
    {
      'name': "heal",
      'description': "Heals you or a friend.",
      'price': 500
    },
    {
      'name': "power",
      'description': "Has an unpredictable effect which is different in every adventure.",
      'price': 100
    },
    {
      'name': "speed",
      'description': "Doubles your agility for a time, making you a better fighter.",
      'price': 4000
    }
  ];

  constructor(private _router: Router,
              private _playerService: PlayerService) {
  }

  ngOnInit() {
    let id = parseInt(window.localStorage.getItem('player_id'));
    this._playerService.getPlayer(id);
  }

  gotoDetail() {
    this._router.navigate(['/hall']);
  }

  buy(spell_name: string) {
    let player = this._playerService.player;
    this.error = "";
    this.message = "";
    let spell = this.spells.find(x => x.name === spell_name);
    if (spell.price > player.gold) {

      this.error = "When Hokas sees that you don't have enough to pay him, he stalks back to the bar, muttering about youngsters who should be turned into frogs.";

    } else if (player.spell_abilities_original[spell.name] >= 90) {

      this.error = 'Hokas says, "I ought to take your gold anyway, but you already know that spell as well as I can teach it!" Shaking his head sadly, he returns to the bar.';

    } else if (player.spell_abilities_original[spell.name]) {
      // improving ability

      this.message = 'Hokas says, "Didn\'t learn it well enough the first time, eh? Well, we could all use a little brushing up." He teaches you some new techniques, takes his fee, and returns to his stool on the bar. As you walk away, you hear him order a Double Dragon Blomb.';
      let possible_increase = 100 - player.spell_abilities_original[spell.name];
      let inc = Math.floor(possible_increase / 4 + Game.getInstance().diceRoll(1, possible_increase / 2));
      player.spell_abilities_original[spell.name] += inc;
      player.gold -= spell.price;

    } else {
      // learning for the first time

      this.message = "Hokas teaches you your spell, takes his fee, and returns to his stool on the bar. As you walk away, you hear him order a Double Dragon Blomb.";
      player.spell_abilities_original[spell.name] = Game.getInstance().diceRoll(1, 50) + 25;
      player.gold -= spell.price;

    }
  }

}
