// static/main-hall/components/player-list.component.ts
import {Component,  OnInit}  from '@angular/core';
import { Router } from '@angular/router';
import { Observable }     from 'rxjs/Observable';

import {Player} from '../models/player';
import {PlayerService} from '../services/player.service';

@Component({
  template: `
  <p>You are in the outer chamber of the hall of the Guild of Free Adventurers. Many men and women are guzzling beer and there is loud singing and laughter.</p>
  <p>On the north side of the chamber is a cubbyhole with a desk. Over the desk is a sign which says: <strong>&quot;REGISTER HERE OR ELSE!&quot;</strong></p>
  <p>Behind the desk is a burly Irishman who looks at you with a scowl and asks, &quot;What's your name?&quot;</p>
  <p>The guest book on the desk lists the following adventurers:</p>
  <div class="row">
    <div class="player col-sm-4" *ngFor="let player of _playerService.players">
      <div class="icon"><img src="/static/images/ravenmore/128/{{ player.icon }}" width="80" height="80"></div>
      <div class="name"><a (click)="gotoPlayer(player)"><strong>{{player.name}}</strong></a><br />
      <small>HD: {{player.hardiness}} AG: {{player.agility}} CH: {{player.charisma}} <br />
      {{player.best_weapon?.name}}</small></div>
      <div class="delete"><a (click)="deletePlayer(player)"><span class="glyphicon glyphicon-trash"></span></a></div>
    </div>
  </div>
  <p *ngIf="_playerService.players?.length == 0">There are no adventurers in the guest book.</p>
  <p class="addplayer"><a [routerLink]="['/register']"><strong>Create a New Adventurer</strong></a></p>
  `
})
export class PlayerListComponent implements OnInit  {

  constructor(
    private _router: Router,
    private _playerService: PlayerService){}

  public ngOnInit(): void {
    this._playerService.getList();
  }

  gotoPlayer(player: Player) {
    this._playerService.enterHall(player.id);
    this._router.navigate( ['/hall'] );
  }

  deletePlayer(player: Player) {
    if (confirm("Are you sure you want to delete " + player.name + "?")) {
      window.localStorage.setItem('player_id', null);
      this._playerService.delete(player).subscribe(
         data => {
           this._playerService.getList();
           return true;
         },
         error => {
           console.error("Error deleting player!");
           return Observable.throw(error);
         });
    }
  }
}

// client/src/components/PlayerList.tsx
import axios from 'axios';
import * as React from 'react';
import Player from '../models/player';
import PlayerListItem from "./PlayerListItem";
import { Link } from "react-router-dom";

class PlayerList extends React.Component {
  public state: any = {
    players: [],
    uuid: ""
  };

  public componentDidMount() {
    const uuid = window.localStorage.getItem('eamon_uuid');
    this.setState({ uuid });
    axios.get('/api/players.json?uuid=' + uuid)
      .then(res => {
        const players = res.data.map(pl => {
          let p = new Player();
          p.init(pl);
          p.update();
          return p;
        });
        this.setState({ players });
      });
  }

  public render() {

    let empty_message = (<span />);
    if (this.state.players.length === 0) {
      empty_message = (<p>There are no adventurers in the guest book.</p>)
    }

    return (
      <div id="PlayerList">
        <p>You are in the outer chamber of the hall of the Guild of Free Adventurers. Many men and women are guzzling beer and there is loud singing and laughter.</p>
        <p>On the north side of the chamber is a cubbyhole with a desk. Over the desk is a sign which says: <strong>&quot;REGISTER HERE OR ELSE!&quot;</strong></p>
        <p>Behind the desk is a burly Irishman who looks at you with a scowl and asks, &quot;What's your name?&quot;</p>
        <p>The guest book on the desk lists the following adventurers:</p>
        <div className="row">
          {this.state.players.map(player => <PlayerListItem key={player.id} player={player} /> )}
        </div>
        {empty_message}
        <p className="addplayer"><Link to="/main-hall/register"><strong>Create a New Adventurer</strong></Link></p>
      </div>
    );
  }
}

export default PlayerList;
